local_backend: true

backend:
  name: proxy
  proxy_url: https://my-decap-auth-test.pages.dev/api/proxy
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Посты"
    folder: "content/english/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime" }
      - { label: "Изображение", name: "image", widget: "image", required: false }
      - { label: "Авторы", name: "authors", widget: "list", required: false }
      - { label: "Текст поста", name: "body", widget: "markdown" }
